Strict

Public

Import IosRequiresFullscreen
Import allowunsecureconnections
Import amazonads
Import amazonpayment
Import androidbass
Import glfwsteam
Import iosaddlanguage
Import iosappodeal
Import iosbundleid
Import ioscocoapods
Import ioscompresspngfiles
Import iosdeploymenttarget
Import iosenablebitcode
Import iosframework
Import ioshidestatusbar
Import iosicons
Import iosinterfaceorientation
Import ioslaunchimage
Import iospatchcodesigningidentity
Import iosproductname
Import iosversion
